remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Panagiotis Mokos
description: Computer Science - Informatics | Data Scientist/Backend Developer
logo: /assets/img/avatar.png
