remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

[cite_start]title: Panagiotis Mokos [cite: 1]
description: Computer Science Student | [cite_start]Technical Support Analyst [cite: 1]
logo: /assets/avatar.jpg
